[profile.default]
src = "evm"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Also compile mocks for testing
extra_output_files = ["abi"]

[rpc_endpoints]
passet = "https://testnet-passet-hub-eth-rpc.polkadot.io"
