// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface IYieldPoolUSDC {
    function balanceOf(
        address user
    ) external view returns (uint256);
    function transfer(
        address to,
        uint256 amount
    ) external returns (bool);
    function transferFrom(
        address from,
        address to,
        uint256 amount
    ) external returns (bool);
    function mint(
        address to,
        uint256 amount
    ) external;
}

/// @notice Mock yield pool for the Kredio intelligent yield strategy.
/// @dev Yield is generated by calling MockUSDC.mint() - valid on testnet only.
///      Yield accrues continuously by timestamp on the deposited principal.
///      Settlement happens on every principal change so the accrued amount is
///      always exact regardless of how many partial withdrawals have occurred.
contract MockYieldPool {
    address public admin;
    IYieldPoolUSDC public usdc;
    uint256 public yieldRateBps;
    uint256 internal constant BPS_DIVISOR = 10_000;

    struct Stake {
        uint256 principal;
        uint256 accrued; // settled yield not yet claimed
        uint256 lastSettledAt; // timestamp when accrued was last updated
    }

    mapping(address => Stake) public stakes;
    uint256 public totalPrincipal;

    event Deposited(address indexed depositor, uint256 amount);
    event Withdrawn(address indexed depositor, address indexed to, uint256 amount);
    event YieldClaimed(address indexed depositor, address indexed to, uint256 amount);
    event YieldRateSet(uint256 rateBps);

    modifier onlyAdmin() {
        require(msg.sender == admin, "not admin");
        _;
    }

    constructor(
        address _usdc,
        uint256 _yieldRateBps
    ) {
        require(_usdc != address(0), "zero addr");
        require(_yieldRateBps <= 100_000, "rate too high"); // max 1000% APY
        admin = msg.sender;
        usdc = IYieldPoolUSDC(_usdc);
        yieldRateBps = _yieldRateBps;
    }

    // ── External ──────────────────────────────────────────────────────────

    /// @notice Deposit mUSDC principal. Caller must have approved this contract first.
    /// @param amount Amount of mUSDC to deposit (6 decimals).
    function deposit(
        uint256 amount
    ) external {
        require(amount > 0, "zero amount");
        _settle(msg.sender);
        stakes[msg.sender].principal += amount;
        totalPrincipal += amount;
        require(usdc.transferFrom(msg.sender, address(this), amount), "transfer fail");
        emit Deposited(msg.sender, amount);
    }

    /// @notice Withdraw principal back to `to`. Does NOT auto-claim yield.
    ///         Any yield accumulated so far is locked into `accrued` and remains
    ///         claimable via claimYield() so no yield is ever silently lost.
    /// @param to   Recipient of the withdrawn principal.
    /// @param amount Amount to withdraw (6 decimals).
    function withdraw(
        address to,
        uint256 amount
    ) external {
        require(amount > 0, "zero amount");
        Stake storage s = stakes[msg.sender];
        require(s.principal >= amount, "insufficient principal");
        _settle(msg.sender); // lock in yield before principal shrinks
        s.principal -= amount;
        if (totalPrincipal >= amount) totalPrincipal -= amount;
        else totalPrincipal = 0;
        require(usdc.transfer(to, amount), "transfer fail");
        emit Withdrawn(msg.sender, to, amount);
    }

    /// @notice Claim all pending yield (accrued store + live since last settle).
    ///         Mints fresh mUSDC directly to `to` - works on testnet because
    ///         MockUSDC.mint() is permissionless.
    /// @param to Recipient of yield (usually the lending contract).
    /// @return amount The yield minted.
    function claimYield(
        address to
    ) external returns (uint256 amount) {
        _settle(msg.sender);
        amount = stakes[msg.sender].accrued;
        require(amount > 0, "no yield");
        stakes[msg.sender].accrued = 0;
        usdc.mint(to, amount);
        emit YieldClaimed(msg.sender, to, amount);
    }

    // ── Views ─────────────────────────────────────────────────────────────

    /// @notice Returns pending yield = stored accrued + live (since last settle).
    function pendingYield(
        address who
    ) public view returns (uint256) {
        Stake storage s = stakes[who];
        uint256 live = 0;
        if (s.principal > 0 && s.lastSettledAt > 0 && block.timestamp > s.lastSettledAt) {
            uint256 elapsed = block.timestamp - s.lastSettledAt;
            live = (s.principal * yieldRateBps * elapsed) / (BPS_DIVISOR * 365 days);
        }
        return s.accrued + live;
    }

    /// @notice Full stake view for dashboards.
    function getStake(
        address who
    ) external view returns (uint256 principal, uint256 accrued, uint256 pending) {
        Stake storage s = stakes[who];
        return (s.principal, s.accrued, pendingYield(who));
    }

    // ── Admin ─────────────────────────────────────────────────────────────

    /// @notice Update APY rate. Use 600 for 6% APY, 60000 for fast demo visibility.
    function setYieldRate(
        uint256 rateBps
    ) external onlyAdmin {
        require(rateBps <= 100_000, "rate too high");
        yieldRateBps = rateBps;
        emit YieldRateSet(rateBps);
    }

    // ── Internal ──────────────────────────────────────────────────────────

    /// @dev Settle all live accrued yield into `accrued` storage and reset clock.
    ///      Must be called before any principal change to preserve yield accuracy.
    function _settle(
        address who
    ) internal {
        Stake storage s = stakes[who];
        if (s.principal > 0 && s.lastSettledAt > 0 && block.timestamp > s.lastSettledAt) {
            uint256 elapsed = block.timestamp - s.lastSettledAt;
            s.accrued += (s.principal * yieldRateBps * elapsed) / (BPS_DIVISOR * 365 days);
        }
        s.lastSettledAt = block.timestamp;
    }
}
